name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --all -- --check
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy -- -D clippy::unwrap_used
    - name: Build
      run: cargo build
    - name: Unit tests
      run: cargo test --lib
    - name: Integration tests
      # test threads must be one because else database tests will run in parallel and will result in flaky tests
      run: cargo test --test '*' -- --test-threads=1

